# Default values for neurobridges.
# This is a YAML-formatted file.
# Declare default variables to be passed into your templates.

replicaCount: 1

image:
  repository: containers.renci.org/sam/segment-any-volume
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: sav.apps.renci.org
      paths:
        - path: /
  tls:
    - secretName: sav.apps.renci.org-tls
      hosts:
        - sav.apps.renci.org

resources: {}
#resources:
#  requests:
#    cpu: 100m
#    memory: 100Mi
#  limits:
#    memory: 200Mi